<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-05 at 14:06:03.
 * @group v1
 */
class Ae_Db_UtlTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Ae_Db_Base
     */
    protected $db;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $db = Ae_Db::of($GLOBALS);
        $db->open();
        $this->db = $db;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        AeTest_Db::drop_all_table($this->db);
        $this->db = null;
    }

    /**
     * @covers Ae_Db_Utl::count
     */
    public function testCount()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ae_Db_Utl::get_record
     * @todo   Implement testGet_record().
     */
    public function testGet_record()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ae_Db_Utl::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ae_Db_Utl::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ae_Db_Utl::insert
     * @todo   Implement testInsert().
     */
    public function testInsert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ae_Db_Utl::get_hour_past
     * @todo   Implement testGet_hour_past().
     */
    public function testGet_hour_past()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ae_Db_Utl::get_past_caption
     * @todo   Implement testGet_past_caption().
     */
    public function testGet_past_caption()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ae_Db_Utl::escape_like
     * @todo   Implement testEscape_like().
     */
    public function testEscape_like()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ae_Db_Utl::select_all
     * @todo   Implement testSelect_all().
     */
    public function testSelect_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ae_Db_Utl::select_where
     */
    public function testSelect_where()
    {
    }
}
