<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-06 at 00:22:07.
 * @group v1
 */
class Ae_Db_PdoMysqlTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Ae_Db_PdoMysql
     */
    protected $db;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $db = Ae_Db::of($GLOBALS);
        $db->open();
        $this->db = $db;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        AeTest_Db::drop_all_table($this->db);
        $this->db = null;
    }

    /**
     * @covers Ae_Db_PdoMysql::open
     * @todo   Implement testOpen().
     */
    public function testOpen()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ae_Db_PdoMysql::lockTable
     * @todo   Implement testLockTable().
     */
    public function testLockTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ae_Db_PdoMysql::unlock
     * @todo   Implement testUnlock().
     */
    public function testUnlock()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ae_Db_PdoMysql::columns
     * @todo   Implement testColumns().
     */
    public function testColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ae_Db_PdoMysql::tables
     * @covers AeTest_Db::create_table_random
     */
    public function testTables()
    {
        $t1 = AeTest_Db::create_table_random($this->db);
        $tables = $this->db->tables();
        $this->assertEquals(array($t1), $tables);
        $this->assertEquals(1, count($tables));
        $t2 = AeTest_Db::create_table_random($this->db);
        $tables = $this->db->tables();
        $this->assertContains($t1, $tables);
        $this->assertContains($t2, $tables);
        $this->assertEquals(2, count($tables));
    }

    /**
     * @covers Ae_Db_PdoMysql::tableExists
     * @covers AeTest_Db::create_table_random
     */
    public function testTableExists()
    {
        $t1 = AeTest_Db::create_table_random($this->db);
        $this->assertTrue($this->db->tableExists($t1));
    }
}
